# -*- coding: utf-8 -*-
"""Assignment2.part2.1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1119AycG3DTNFXHeKfur2fODOwjnNHvbc
"""

import numpy as np
import matplotlib.pyplot as plt
import os

filepath = os.getcwd()
data1 = os.path.join(filepath, "mnist_test.csv")
data2 = os.path.join(filepath, "mnist_train.csv")

test_data = np.genfromtxt(
    data1, 
    dtype=np.unicode_, 
    delimiter=",", 
    skip_header=1, 
    encoding="utf-8-sig"
)

train_data = np.genfromtxt(
    data2, 
    dtype=np.unicode_, 
    delimiter=",", 
    skip_header=1,
    encoding="utf-8-sig"
)

test_data.shape

fac = 0.99 / 255
train_imgs = np.asfarray(train_data[:, 1:]) * fac + 0.01
test_imgs = np.asfarray(test_data[:, 1:]) * fac + 0.01

train_labels = np.asfarray(train_data[:, :1])
test_labels = np.asfarray(test_data[:, :1])

for i in range(5):
    img = train_imgs[i].reshape((28,28))
    plt.imshow(img, cmap="Greys")
    plt.show()

img = train_imgs[2].reshape((28,28))
img_transposed=img.T
plt.imshow(img, cmap="Greys")
plt.show()
plt.imshow(img_transposed, cmap="Greys")
plt.show()

#c
batch=train_imgs[:10]
batch=batch.reshape(-1,)
print(batch.shape)

#d
batch=batch.reshape(-1,28)
plt.imshow(batch)
plt.show()

#e
def showImagesHorizontally(list_of_files):
    fig = figure()
    number_of_files = len(list_of_files)
    for i in range(number_of_files):
        a=fig.add_subplot(1,number_of_files,i+1)
        image = imread(list_of_files[i])
        plt.imshow(image,cmap='Greys_r')
        plt.axis('off')
        plt.show()
batch=batch.reshape(10,-1)
plt.imshow(batch)
plt.show()
imgs=batch[0].reshape(28,28)
for i in batch[1:]:
  imgs=np.hstack((imgs,i.reshape(28,28)))
plt.imshow(imgs)
plt.show()

#f
print(imgs.shape)
imgH1 = imgs[: , 0:int(imgs.shape[1]/2)]
imgH2 = imgs[: , int(imgs.shape[1]/2):]
plt.imshow(imgH1)
plt.show()
plt.imshow(imgH2)







